# Generated by Django 4.2.15 on 2024-08-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_de_cuisine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='plat',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
